name: GKI SCCACHE | DoraCore Kernel Build

on:
  workflow_dispatch:
    inputs:
      KERNEL_BRANCH:
        description: 'DoraCore Branch'
        required: true
        default: 'Rebase'
        type: choice
        options:
        - Rebase
        - Rebase-CAF
      KERNEL_GIT:
        description: 'Kernel Source Code'
        required: true
        default: 'https://github.com/tungtx57-pixel/android_kernel_xiaomi_common.git'
      BUILD_DEVICE:
        description: 'Device Target'
        required: true
        default: 'mayfly'
        type: choice
        options:
        - all
        - mayfly
        - cupid
        - unicorn
        - zeus
        - diting
        - marble
        - mondrian
        - thor
        - zizhan
        - ziyi
        - ingres
        - gki
      MANIFEST_GIT:
        description: 'Kernel Manifest Git'
        required: true
        default: 'https://github.com/tungtx57-pixel/android_kernel_xiaomi_common.git'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'KittiSU'
        type: choice
        options:
        - KittiSU
        - NonKSU
        - KSU
        - Both
      KITTISU_BRANCH:
        description: 'KittiSU Branch (terebiko/kittisu)'
        required: true
        default: 'main'
        type: choice
        options:
        - main
        - dev
      ENABLE_SUSFS:
        description: 'Enable SUSFS Patch (Bật/Tắt SUSFS)'
        required: true
        default: 'Enable'
        type: choice
        options:
        - Enable
        - Disable
      USING_CCACHE:
        description: 'Using CCACHE'
        required: true
        default: 'Enable'
        type: choice
        options:
        - Enable
        - Disable
      CLEAN_CCACHE:
        description: 'Clean CCACHE'
        required: true
        default: 'Disable'
        type: choice
        options:
        - Enable
        - Disable
      BUILDING_CCACHE:
        description: 'Building CCACHE'
        required: true
        default: 'Disable'
        type: choice
        options:
        - Enable
        - Disable
      RELEASE:
        description: 'Status Release'
        required: true
        default: 'draft'
        type: choice
        options:
        - draft
        - prerelease
        - release

jobs:
  cache-clear:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clean CCACHE
        if: github.event.inputs.CLEAN_CCACHE == 'Enable'
        uses: easimon/wipe-cache@main

  set-matrix:
    needs: cache-clear
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Matrix Setup
        id: set-matrix
        shell: bash
        env:
          BUILD_DEVICE: ${{ github.event.inputs.BUILD_DEVICE }}
        run: |
          if [ "$BUILD_DEVICE" = "mayfly" ]; then
            matrix='["mayfly"]'
          elif [ "$BUILD_DEVICE" = "cupid" ]; then
            matrix='["cupid"]'
          elif [ "$BUILD_DEVICE" = "zeus" ]; then
            matrix='["zeus"]'
          elif [ "$BUILD_DEVICE" = "unicorn" ]; then
            matrix='["unicorn"]'
          elif [ "$BUILD_DEVICE" = "diting" ]; then
            matrix='["diting"]'
          elif [ "$BUILD_DEVICE" = "marble" ]; then
            matrix='["marble"]'
          elif [ "$BUILD_DEVICE" = "mondrian" ]; then
            matrix='["mondrian"]'
          elif [ "$BUILD_DEVICE" = "thor" ]; then
            matrix='["thor"]'
          elif [ "$BUILD_DEVICE" = "zizhan" ]; then
            matrix='["zizhan"]'
          elif [ "$BUILD_DEVICE" = "ziyi" ]; then
            matrix='["ziyi"]'
          elif [ "$BUILD_DEVICE" = "ingres" ]; then
            matrix='["ingres"]'
          elif [ "$BUILD_DEVICE" = "gki" ]; then
            matrix='["gki"]'
          elif [ "$BUILD_DEVICE" = "all" ]; then
            matrix='["mayfly", "cupid", "unicorn", "zeus", "diting", "marble", "mondrian", "thor", "zizhan", "ziyi", "ingres", "gki"]'
          fi

          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  create_release:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set tag as timestamp
        id: set-tag
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-tag.outputs.tag }}
          name: DoraCore Build ${{ steps.set-tag.outputs.tag }}
          draft: ${{ github.event.inputs.RELEASE == 'draft' }}
          prerelease: ${{ github.event.inputs.RELEASE == 'prerelease' }}
          make_latest: ${{ github.event.inputs.RELEASE == 'release' }}
          body: |
            Build: DoraCore Kernel For GKI Linux 5.10.y
            Linux: Linux 5.10.y
            Type: GKI
            Developer: dopaemon
            Credits: ArianK16a, bachnxuan, Gelbpunkt, ztc1997, pzqqt, KernelToast, Arter97, ramabondanp, Gosth15, Flopster101, bheatleyyy, keosh1, n08i40k, ParsaAslaniYC, ...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [create_release, set-matrix]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: ${{ fromJson(needs.set-matrix.outputs.matrix) }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check Initial Disk Space
        run: |
          echo "===== Initial Total Disk Space in GB ====="
          df -BG

      - name: Clean-up
        uses: rokibhasansagar/slimhub_actions@main

      - name: Check Disk Space After Cleanup
        run: |
          echo "===== Total Disk Space After Cleanup in GB ====="
          df -BG

      - name: Build Environment
        run: |
          TARGET="${{ github.event.inputs.BUILD_TARGET }}"
          echo "BUILD_DATE=$(TZ=Asia/Ho_Chi_Minh date +'%Y-%m%d-%H%M')" >> $GITHUB_ENV
          sudo apt-mark hold firefox
          sudo apt-mark hold libc-bin
          sudo apt purge man-db
          sudo rm -rf /var/lib/man-db/auto-update
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            curl bison flex make binutils git perl gcc python3 \
            python-is-python3 bc libssl-dev libelf-dev \
            bc aria2 zip unzip ccache binutils-aarch64-linux-gnu \
            tar which wget zip unzip sccache ca-certificates

          cd $GITHUB_WORKSPACE
          sudo wget -O /usr/bin/repo http://commondatastorage.googleapis.com/git-repo-downloads/repo
          sudo chmod +x /usr/bin/repo
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          mkdir -p $GITHUB_WORKSPACE/android-kernel && cd $GITHUB_WORKSPACE/android-kernel
          repo init --depth=1 -u ${{ github.event.inputs.KERNEL_GIT }} -b manifest
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          git clone -b build --single-branch --depth=1 https://github.com/tungtx57-pixel/android_kernel_xiaomi_common.git build
          rm -rf .git .github .repo common
          rm -rf ./build/_setup_env.sh
          wget -O ./build/_setup_env.sh https://raw.githubusercontent.com/tungtx57-pixel/android_kernel_xiaomi_common/refs/heads/master/.github/scripts/_setup_env.sh
          chmod +x ./build/_setup_env.sh
          if [ "$TARGET" != "Both" ]; then
             git clone -b master --depth=1 --single-branch https://github.com/dopaemon/Anykernel3.git ./AnyKernel3
          else
             git clone -b volume --depth=1 --single-branch https://github.com/dopaemon/Anykernel3.git ./AnyKernel3
          fi
          rm -rf ./AnyKernel3/.git
          rm -rf ${{ github.workspace }}/android-kernel/prebuilts/build-tools
          rm -rf ${{ github.workspace }}/android-kernel/prebuilts/kernel-build-tools
          cd ${{ github.workspace }}/android-kernel/prebuilts
          git clone -b build-tools --single-branch --depth=1 https://github.com/tungtx57-pixel/android_kernel_xiaomi_common.git ${{ github.workspace }}/android-kernel/prebuilts/build-tools
          git clone -b build-tools --single-branch --depth=1 https://github.com/tungtx57-pixel/android_kernel_xiaomi_common.git ${{ github.workspace }}/android-kernel/prebuilts/kernel-build-tools

      - name: Install Docker
        run: |
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
          EOF
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Get SM8450 Trees
        run: |
          git clone -b lineage-23.0 \
              --single-branch \
              --depth=1 \
              https://github.com/dopaemon/android_kernel_xiaomi_sm8450-devicetrees.git \
              $GITHUB_WORKSPACE/android-kernel/sm8450-devicetrees

          git clone -b lineage-23.0 \
              --single-branch \
              --depth=1 \
              https://github.com/dopaemon/android_kernel_xiaomi_sm8450-modules.git \
              $GITHUB_WORKSPACE/android-kernel/sm8450-modules

      - name: Cache Kernel
        if: github.event.inputs.USING_CCACHE == 'Enable'
        id: cache-kernel
        uses: actions/cache@v4
        with:
          path: android-kernel/common
          key: kernel-${{ github.event.inputs.KERNEL_BRANCH }}
          restore-keys: |
            kernel-

      - name: Clone Kernel if cache missed
        if: steps.cache-kernel.outputs.cache-hit != 'true'
        run: |
          rm -rf android-kernel/common
          git clone -b ${{ github.event.inputs.KERNEL_BRANCH }} --recurse-submodules -j$(nproc --all) --single-branch --no-tags ${{ github.event.inputs.KERNEL_GIT }} android-kernel/common

      - name: Sync Kernel if cache complete
        if: steps.cache-kernel.outputs.cache-hit == 'true'
        run: |
          cd android-kernel/common
          git fetch origin ${{ github.event.inputs.KERNEL_BRANCH }}
          git reset --hard FETCH_HEAD
          git submodule update --init --recursive

      - name: Setup KittiSU
        if: github.event.inputs.BUILD_TARGET != 'NonKSU'
        run: |
          cd $GITHUB_WORKSPACE/android-kernel/common
          echo ">>> Setting up KittiSU (${{ github.event.inputs.KITTISU_BRANCH }})..."
          curl -LSs "https://raw.githubusercontent.com/terebiko/kittisu/${{ github.event.inputs.KITTISU_BRANCH }}/kernel/setup.sh" | bash -s ${{ github.event.inputs.KITTISU_BRANCH }}

      - name: Cache Clang
        if: github.event.inputs.USING_CCACHE == 'Enable'
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: android-kernel/prebuilts-master/clang/host/linux-x86/clang-r416183b
          key: clang-${{ github.event.inputs.KERNEL_BRANCH }}
          restore-keys: |
            clang-

      - name: Clone Clang if cache missed
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          mkdir -p $GITHUB_WORKSPACE/android-kernel/prebuilts-master/clang/host/linux-x86
          cd $GITHUB_WORKSPACE/android-kernel/prebuilts-master/clang/host/linux-x86/
          git clone -b 21 --single-branch --depth=1 https://gitlab.com/vantoman/playground-clang.git clang-r416183b

      - name: Setup Enviroment
        run: |
          export PATH="${{ github.workspace }}/android-kernel/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:$PATH"
          export PATH="${{ github.workspace }}/android-kernel/prebuilts/build-tools/bin:$PATH"
          CLANG_DIR="${{ github.workspace }}/android-kernel/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin"
          CLANG_VERSION="$($CLANG_DIR/clang --version | head -n 1)"
          LLD_VERSION="$($CLANG_DIR/ld.lld --version | head -n 1)"
          echo "Prebuilts Infomation:"
          echo "Clang Version: $CLANG_VERSION"
          echo "LLD Version: $LLD_VERSION"

      - name: First Setup SCCACHE
        run: |
          SCCACHE_DIR="${{ github.workspace }}/sccache"
          mkdir -p $SCCACHE_DIR
          sudo chmod 7777 $SCCACHE_DIR
          echo "SCCACHE_DIR=$SCCACHE_DIR" >> $GITHUB_ENV
          echo "SCCACHE_BASEDIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Get Cache SCCACHE
        if: github.event.inputs.USING_CCACHE == 'Enable'
        id: cache-sccache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/sccache
          key: sccache-${{ github.event.inputs.KERNEL_BRANCH }}
          restore-keys: |
            sccache-

      - name: Get Redis
        if: github.event.inputs.USING_CCACHE == 'Enable'
        id: cache-redis
        uses: actions/cache@v4
        with:
          path: /data
          key: redis-${{ github.event.inputs.KERNEL_BRANCH }}-
          restore-keys: |
            redis-${{ github.event.inputs.KERNEL_BRANCH }}-

      - name: Setup Docker First Time
        if: steps.cache-redis.outputs.cache-hit != 'true'
        run: |
          sudo docker run \
                      --name=redis \
                      -d \
                      -p 6379:6379 \
                      redis

      - name: Setup Docker When Cache
        if: steps.cache-redis.outputs.cache-hit == 'true'
        run: |
          sudo docker run \
                      --name=redis \
                      -d \
                      -p 6379:6379 \
                      -v /data/sccache.rdb:/data/dump.rdb \
                      redis

      - name: Complete Setup SCCACHE
        run: |
          export SCCACHE_REDIS="redis://127.0.0.1:6379"
          export SCCACHE_CACHE_SIZE="5G"
          export SCCACHE_IDLE_TIMEOUT=0
          sccache --start-server
          sccache --show-stats
          echo 'SCCACHE_REDIS="redis://127.0.0.1:6379"' >> $GITHUB_ENV
          echo 'SCCACHE_CACHE_SIZE="5G"' >> $GITHUB_ENV
          echo 'SCCACHE_IDLE_TIMEOUT=0' >> $GITHUB_ENV

      - name: Fakestats - Faketime
        run: |
          export FAKESTAT="2025-05-25 12:00:00"
          export FAKETIME="@2025-05-25 13:00:00"
          echo "FAKESTAT=$FAKESTAT" >> $GITHUB_ENV
          echo "FAKETIME=$FAKETIME" >> $GITHUB_ENV

      - name: Build Selected Devices KSU
        if: (github.event.inputs.BUILD_TARGET == 'KittiSU' || github.event.inputs.BUILD_TARGET == 'KSU' || github.event.inputs.BUILD_TARGET == 'Both') && (github.event.inputs.KERNEL_BRANCH == 'Rebase' || github.event.inputs.KERNEL_BRANCH == 'Rebase-CAF')
        run: |
          set -e
          DEVICE="${{ matrix.device }}"
          TARGET="${{ github.event.inputs.BUILD_TARGET }}"
          ZIP_NAME=""
          rm -rf $GITHUB_WORKSPACE/android-kernel/out

          export KERNEL_USE_SCCACHE=1
          export KERNEL_USE_CCACHE=0

          export PATH="${{ github.workspace }}/android-kernel/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:$PATH"
          export PATH="${{ github.workspace }}/android-kernel/prebuilts/build-tools/bin:$PATH"
          export PRELOAD_LIBS="$GITHUB_WORKSPACE/android-kernel/prebuilts/build-tools/lib64/libfakestat.so $GITHUB_WORKSPACE/android-kernel/prebuilts/build-tools/lib64/libfaketimeMT.so"

          unset DTC
          export DTC="${{ github.workspace }}/android-kernel/prebuilts/build-tools/bin/dtc"

          cd $GITHUB_WORKSPACE/android-kernel
          cd ./common/
          git add -vA
          git reset --hard HEAD
          if [ "${{ github.event.inputs.BUILD_TARGET }}" != "NonKSU" ]; then
             echo ">>> Setting up KittiSU (${{ github.event.inputs.KITTISU_BRANCH }})..."
             curl -LSs "https://raw.githubusercontent.com/tungtx57-pixel/KittiSU-Bomb/${{ github.event.inputs.KITTISU_BRANCH }}/kernel/setup.sh" | bash -s ${{ github.event.inputs.KITTISU_BRANCH }}
          fi
          rm -rf $GITHUB_WORKSPACE/android-kernel/out/android12-5.10
          echo "CONFIG_KSU=y" >> arch/arm64/configs/gki_defconfig

          if [ "${{ github.event.inputs.ENABLE_SUSFS }}" = "Enable" ]; then
             echo "CONFIG_KSU_SUSFS_INLINE_HOOK=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_HAS_SU_COMPAT=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> arch/arm64/configs/gki_defconfig
             VARIANT_NAME="KittiSU-SUSFS"
          elif [ "${{ github.event.inputs.KERNEL_BRANCH }}" = "Rebase-CAF" ]; then
             echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS=n" >> arch/arm64/configs/gki_defconfig
             VARIANT_NAME="KittiSU"
          else
             echo "CONFIG_KSU_TRACEPOINT_HOOK=y" >> arch/arm64/configs/gki_defconfig
             echo "CONFIG_KSU_SUSFS=n" >> arch/arm64/configs/gki_defconfig
             VARIANT_NAME="KittiSU"
          fi

          rm -rf *-wrapper
          rm -rf test-wrapper.sh
          touch cc-wrapper
          touch ld-wrapper
          chmod +x *-wrapper
          echo '#!/bin/bash' > cc-wrapper
          echo 'sccache clang "$@"' >> cc-wrapper
          echo '#!/bin/bash' > ld-wrapper
          echo 'ld.lld "$@"' >> ld-wrapper
          touch test-wrapper.sh
          chmod +x test-wrapper.sh
          echo '#!/bin/bash' > test-wrapper.sh
          echo 'echo ">>> Wrapper check enviroment."' >> test-wrapper.sh
          echo 'exec "$@"' >> test-wrapper.sh
          chmod +x test-wrapper.sh
          ./test-wrapper.sh date
          ./test-wrapper.sh stat ./Makefile
          chmod +x cc-wrapper ld-wrapper

          rm ./android/abi_gki_protected_exports_* || true

          if [ "$DEVICE" != "gki" ]; then
             cat arch/arm64/configs/vendor/waipio_GKI.config >> arch/arm64/configs/gki_defconfig
             cat arch/arm64/configs/vendor/xiaomi_GKI.config >> arch/arm64/configs/gki_defconfig
             cat arch/arm64/configs/vendor/"$DEVICE"_GKI.config >> arch/arm64/configs/gki_defconfig
             cat arch/arm64/configs/vendor/debugfs.config >> arch/arm64/configs/gki_defconfig
          fi

          export DTC=$(pwd)/scripts/dtc/dtc

          make -j$(nproc --all) \
               LLVM=1 \
               ARCH=arm64 \
               CROSS_COMPILE="aarch64-linux-gnu-" \
               CC="sccache clang" \
               O=$GITHUB_WORKSPACE/android-kernel/out \
               LLVM_IAS=1 \
               DTC_EXT=dtc \
               gki_defconfig

          time make -j$(nproc --all) \
               LLVM=1 \
               ARCH=arm64 \
               CROSS_COMPILE="aarch64-linux-gnu-" \
               CC="$(pwd)/cc-wrapper" \
               LD="$(pwd)/ld-wrapper" \
               O=$GITHUB_WORKSPACE/android-kernel/out \
               LLVM_IAS=1 \
               DTC_EXT=dtc \
               DTC_FLAGS="-Wno-all" \
               Image

          [ -f "$GITHUB_WORKSPACE/android-kernel/out/arch/arm64/boot/Image" ] || { exit 1; }

          sudo mkdir -p /data/
          sudo rm -rf /data/*
          sudo docker exec redis redis-cli SAVE
          sudo docker cp redis:/data/dump.rdb /data/sccache.rdb
          sudo chmod 7777 /data/sccache.rdb
          sudo chmod 7777 /data

          cd $GITHUB_WORKSPACE/android-kernel
          cd ./common/

          if [ "$TARGET" != "Both" ]; then
             ZIP_NAME="DoraCore-${DEVICE}-${VARIANT_NAME}-5.10-A12-${BUILD_DATE}.zip"
             cd $GITHUB_WORKSPACE/android-kernel/AnyKernel3
             cp -r $GITHUB_WORKSPACE/android-kernel/out/arch/arm64/boot/Image ./Image
             zip -r9 "$ZIP_NAME" *
             mv "$ZIP_NAME" $GITHUB_WORKSPACE/
          else
             cd $GITHUB_WORKSPACE/android-kernel/AnyKernel3
             cp -r $GITHUB_WORKSPACE/android-kernel/out/arch/arm64/boot/Image ./Image-kittisu
          fi

      - name: Build Selected Devices NonKSU
        if: (github.event.inputs.BUILD_TARGET == 'NonKSU' || github.event.inputs.BUILD_TARGET == 'Both') && (github.event.inputs.KERNEL_BRANCH == 'Rebase' || github.event.inputs.KERNEL_BRANCH == 'Rebase-CAF')
        run: |
          set -e
          DEVICE="${{ matrix.device }}"
          TARGET="${{ github.event.inputs.BUILD_TARGET }}"
          ZIP_NAME=""
          rm -rf $GITHUB_WORKSPACE/android-kernel/out

          export KERNEL_USE_SCCACHE=1
          export KERNEL_USE_CCACHE=0

          export PATH="${{ github.workspace }}/android-kernel/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:$PATH"
          export PATH="${{ github.workspace }}/android-kernel/prebuilts/build-tools/bin:$PATH"
          export PRELOAD_LIBS="$GITHUB_WORKSPACE/android-kernel/prebuilts/build-tools/lib64/libfakestat.so $GITHUB_WORKSPACE/android-kernel/prebuilts/build-tools/lib64/libfaketimeMT.so"

          unset DTC
          export DTC="${{ github.workspace }}/android-kernel/prebuilts/build-tools/bin/dtc"

          cd $GITHUB_WORKSPACE/android-kernel
          cd ./common/
          git add -vA
          git reset --hard HEAD
          rm -rf $GITHUB_WORKSPACE/android-kernel/out/android12-5.10
          echo "CONFIG_KSU=n" >> arch/arm64/configs/gki_defconfig

          rm -rf *-wrapper
          rm -rf test-wrapper.sh
          touch cc-wrapper
          touch ld-wrapper
          chmod +x *-wrapper
          echo '#!/bin/bash' > cc-wrapper
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> cc-wrapper
          echo 'export FAKESTAT="'$FAKESTAT'"' >> cc-wrapper
          echo 'export FAKETIME="'$FAKETIME'"' >> cc-wrapper
          echo 'sccache clang "$@"' >> cc-wrapper
          echo '#!/bin/bash' > ld-wrapper
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> ld-wrapper
          echo 'export FAKESTAT="'$FAKESTAT'"' >> ld-wrapper
          echo 'export FAKETIME="'$FAKETIME'"' >> ld-wrapper
          echo 'ld.lld "$@"' >> ld-wrapper
          touch test-wrapper.sh
          chmod +x test-wrapper.sh
          echo '#!/bin/bash' > test-wrapper.sh
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> test-wrapper.sh
          echo 'export FAKESTAT="'$FAKESTAT'"' >> test-wrapper.sh
          echo 'export FAKETIME="'$FAKETIME'"' >> test-wrapper.sh
          echo 'echo ">>> Wrapper check enviroment."' >> test-wrapper.sh
          echo 'exec "$@"' >> test-wrapper.sh
          chmod +x test-wrapper.sh
          ./test-wrapper.sh date
          ./test-wrapper.sh stat ./Makefile
          chmod +x cc-wrapper ld-wrapper
          LD_PRELOAD=$PRELOAD_LIBS stat ./Makefile

          rm ./android/abi_gki_protected_exports_* || true

          if [ "$DEVICE" != "gki" ]; then
             cat arch/arm64/configs/vendor/waipio_GKI.config >> arch/arm64/configs/gki_defconfig
             cat arch/arm64/configs/vendor/xiaomi_GKI.config >> arch/arm64/configs/gki_defconfig
             cat arch/arm64/configs/vendor/"$DEVICE"_GKI.config >> arch/arm64/configs/gki_defconfig
             cat arch/arm64/configs/vendor/debugfs.config >> arch/arm64/configs/gki_defconfig
          fi

          export DTC=$(pwd)/scripts/dtc/dtc

          make -j$(nproc --all) \
               LLVM=1 \
               ARCH=arm64 \
               CROSS_COMPILE="aarch64-linux-gnu-" \
               CC="sccache clang" \
               O=$GITHUB_WORKSPACE/android-kernel/out \
               LLVM_IAS=1 \
               DTC_EXT=dtc \
               gki_defconfig

          time make -j$(nproc --all) \
               LLVM=1 \
               ARCH=arm64 \
               CROSS_COMPILE="aarch64-linux-gnu-" \
               CC="$(pwd)/cc-wrapper" \
               LD="$(pwd)/ld-wrapper" \
               O=$GITHUB_WORKSPACE/android-kernel/out \
               LLVM_IAS=1 \
               DTC_EXT=dtc \
               DTC_FLAGS="-Wno-all" \
               Image

          [ -f "$GITHUB_WORKSPACE/android-kernel/out/arch/arm64/boot/Image" ] || { exit 1; }

          sudo mkdir -p /data/
          sudo rm -rf /data/*
          sudo docker exec redis redis-cli SAVE
          sudo docker cp redis:/data/dump.rdb /data/sccache.rdb
          sudo chmod 7777 /data/sccache.rdb
          sudo chmod 7777 /data

          if [ "$TARGET" != "Both" ]; then
             ZIP_NAME="DoraCore-${DEVICE}-NonKSU-5.10-A12-${BUILD_DATE}.zip"
             cd $GITHUB_WORKSPACE/android-kernel/AnyKernel3
             cp -r $GITHUB_WORKSPACE/android-kernel/out/arch/arm64/boot/Image ./Image
             zip -r9 "$ZIP_NAME" *
             mv "$ZIP_NAME" $GITHUB_WORKSPACE/
          else
             cd $GITHUB_WORKSPACE/android-kernel/AnyKernel3
             cp -r $GITHUB_WORKSPACE/android-kernel/out/arch/arm64/boot/Image ./Image-standard
          fi

      - name: Create Flashable Both Image
        if: github.event.inputs.BUILD_TARGET == 'Both' && github.event.inputs.KERNEL_BRANCH != 'lindroid'
        run: |
          DEVICE="${{ matrix.device }}"
          ZIP_NAME="DoraCore-${DEVICE}-5.10-A12-${BUILD_DATE}.zip"
          cd $GITHUB_WORKSPACE/android-kernel/AnyKernel3
          zip -r9 "$ZIP_NAME" *
          mv "$ZIP_NAME" $GITHUB_WORKSPACE/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create_release.outputs.tag }}
          draft: ${{ github.event.inputs.RELEASE == 'draft' }}
          prerelease: ${{ github.event.inputs.RELEASE == 'prerelease' }}
          make_latest: ${{ github.event.inputs.RELEASE == 'release' }}
          files: DoraCore*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
